export const skills = [
  "Typescript, JavaScript",
  "React, Redux-toolkit",
  "React Router, React Query, React Hook Form",
  "Next.js, SSR, SSG",
  "HTML5, CSS3, Sass, BEM, Material UI, Tailwind, Bulma",
  "Fetch, REST API, Axios",
  "Git, Webpack, Gulp, Vite, Babel, Eslint, Prettier",
  "Algorithms: Solved 140 katas on CodeWars",
  "ClickUp, Jira, Trello",
  "Basic OOP understanding",
  "Knowledge of SDLC, Waterfall, Agile concepts (Scrum, Kanban)",
  "Experience in leading team projects effectively",
  "English: B1, Polish: A1",
];
